# Generated by Django 3.2.18 on 2023-04-19 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import location_field.models.plain


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('VOLUNTEERING', 'Volunteering'), ('FUNCRAISING', 'Fundraising')], max_length=20)),
                ('category', models.CharField(choices=[('ANIMAL WELFARE', 'Animal Welfare'), ('EDUCATIONAL', 'Educational'), ('ENVIRONMENTAL', 'Environmental'), ('HEALTCARE', 'Healthcare'), ('HUMANRIGHTS', 'Human Rights')], max_length=20)),
                ('summary', models.TextField(help_text='Enter a short summary of your event')),
                ('description', models.TextField(help_text='Enter a full description of your event')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owened_event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
