# Generated by Django 3.2.18 on 2023-04-19 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
