# Generated by Django 3.2.18 on 2023-04-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventorganizer', '0002_auto_20230420_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
